image: golang:1.13

pipelines:
  default:
    - step:
        script: 
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_FULL_NAME}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - apt-get update
          - apt-get install -y x11vnc xvfb
          - cd "${PACKAGE_PATH}"
          - go get -v
          - go build -v
          - go test -v
